# Generated by Django 6.0.6 on 2026-06-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Insights'},
        ),
    ]
