# Generated by Django 6.0.7 on 2026-07-13 06:33

import apps.dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_insight_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(db_index=True, max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('aliases', models.JSONField(default=apps.dashboard.models._empty_list)),
                ('competitors', models.JSONField(default=apps.dashboard.models._empty_list)),
                ('setup_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField()),
                ('tracked_models', models.JSONField(default=apps.dashboard.models._empty_list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='dashboard.aipromptlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
