# Generated by Django 6.0.7 on 2026-07-13 09:11

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_aipromptlist_aitarget_aiprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField(default=apps.dashboard.models._empty_dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
