# Generated by Django 6.0.7 on 2026-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_projectsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataforseo_balance', models.FloatField(blank=True, null=True)),
                ('balance_checked_at', models.DateTimeField(blank=True, null=True)),
                ('low_balance_notified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('kind', models.CharField(choices=[('connection_fail', 'Connection failure'), ('sync_success', 'Sync succeeded'), ('sync_error', 'Sync failed'), ('budget', 'Budget'), ('balance', 'DataForSEO balance'), ('user_added', 'Team member added')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
