# Generated by Django 6.0.6 on 2026-06-11 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(db_index=True, max_length=255)),
                ('scope', models.CharField(default='all', max_length=50)),
                ('status', models.CharField(db_index=True, default='running', max_length=20)),
                ('current_connector', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('records_written', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(db_index=True, max_length=100)),
                ('site_url', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(default='never', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('records_written', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connector', 'site_url'), name='uq_synclog_connector_site')],
            },
        ),
    ]
