# Generated by Django 6.0.6 on 2026-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshrun',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='refreshrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('never', 'Never synced'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='never', max_length=20),
        ),
    ]
