# Generated by Django 6.0.7 on 2026-07-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_refreshrun_options_alter_refreshrun_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshrun',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
