# Generated by Django 6.0.7 on 2026-08-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_refreshrun_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshrun',
            name='skipped_connectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='refreshrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=20),
        ),
    ]
