# Generated by Django 6.0.7 on 2026-08-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_refreshrun_skipped_connectors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshrun',
            name='skipped_connectors',
        ),
    ]
