# Generated by Django 6.0.7 on 2026-08-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_remove_refreshrun_skipped_connectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshrun',
            name='site_pk',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
