# Generated by Django 6.0.7 on 2026-08-07 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_refreshrun_site_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refreshrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('site_url',), name='one_running_refresh_per_site'),
        ),
    ]
